### 3. PyTorch的安装

In [1]:
import torch  
torch.__version__

'1.12.1'

### 4. pytorch基础

In [2]:
x_tensor = torch.ones(5, 3,dtype=torch.float64)
print(x_tensor)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [3]:
x_tensor.numel()

15

In [4]:
import numpy as np
np.random.seed(1)
y_array= np.random.randn(5,3)
y_tensor = torch.from_numpy(y_array)
print(y_tensor)

tensor([[ 1.6243, -0.6118, -0.5282],
        [-1.0730,  0.8654, -2.3015],
        [ 1.7448, -0.7612,  0.3190],
        [-0.2494,  1.4621, -2.0601],
        [-0.3224, -0.3841,  1.1338]], dtype=torch.float64)


In [5]:
result = torch.add(x_tensor,y_tensor)
print(result)

tensor([[ 2.6243,  0.3882,  0.4718],
        [-0.0730,  1.8654, -1.3015],
        [ 2.7448,  0.2388,  1.3190],
        [ 0.7506,  2.4621, -1.0601],
        [ 0.6776,  0.6159,  2.1338]], dtype=torch.float64)


In [6]:
x_tensor.add_(y_tensor)
print(x_tensor)

tensor([[ 2.6243,  0.3882,  0.4718],
        [-0.0730,  1.8654, -1.3015],
        [ 2.7448,  0.2388,  1.3190],
        [ 0.7506,  2.4621, -1.0601],
        [ 0.6776,  0.6159,  2.1338]], dtype=torch.float64)


In [7]:
y_tensor

tensor([[ 1.6243, -0.6118, -0.5282],
        [-1.0730,  0.8654, -2.3015],
        [ 1.7448, -0.7612,  0.3190],
        [-0.2494,  1.4621, -2.0601],
        [-0.3224, -0.3841,  1.1338]], dtype=torch.float64)

In [8]:
torch.manual_seed(1)
x_tensor = torch.randn(4, 4)
print(x_tensor)

tensor([[-1.5256, -0.7502, -0.6540, -1.6095],
        [-0.1002, -0.6092, -0.9798, -1.6091],
        [-0.7121,  0.3037, -0.7773, -0.2515],
        [-0.2223,  1.6871,  0.2284,  0.4676]])


In [9]:
x_tensor = torch.randn(1, 4)
print(x_tensor)
y_tensor = torch.randn(4, 1)
print(y_tensor)

tensor([[-1.0276, -0.5631, -0.8923, -0.0583]])
tensor([[-0.1955],
        [-0.9656],
        [ 0.4224],
        [ 0.2673]])


In [10]:
torch.matmul(x_tensor,y_tensor)

tensor([[0.3521]])

In [13]:
x_tensor[:,1]

tensor([-0.5631])

In [15]:
x_tensor = torch.randn(4, 4)
z_tensor = x_tensor.view(-1, 8) 
z_tensor.shape

torch.Size([2, 8])

In [16]:
z_tensor.tolist()

[[1.8793457746505737,
  -0.07213178277015686,
  0.15777060389518738,
  -0.7734549045562744,
  0.1990565061569214,
  0.04570277780294418,
  0.15295691788196564,
  -0.47567880153656006],
 [-0.11101982742547989,
  0.2927352488040924,
  -0.1578451544046402,
  -0.028787139803171158,
  2.3571109771728516,
  -1.0373387336730957,
  1.5747981071472168,
  -0.6298472285270691]]

In [17]:
z_tensor.numpy()

array([[ 1.8793458 , -0.07213178,  0.1577706 , -0.7734549 ,  0.1990565 ,
         0.04570278,  0.15295692, -0.4756788 ],
       [-0.11101983,  0.29273525, -0.15784515, -0.02878714,  2.357111  ,
        -1.0373387 ,  1.5747981 , -0.6298472 ]], dtype=float32)

In [18]:
x = torch.tensor(3.0, requires_grad=True) # 定义一个值为3的tensor名字叫作x
y = x*x   # 定义y和x的关系
y.backward()  # 自动计算梯度
print(x.grad) #打印y相对于x的梯度

tensor(6.)


In [19]:
z = x*x
z.backward()  
print(x.grad) 

tensor(12.)


In [20]:
x.grad.zero_()
z = x*x
z.backward()  
print(x.grad) 

tensor(6.)


In [21]:
x.grad.data.tolist()

6.0

### 练习

In [23]:
def min_gred(x_start, rate, num, f):
    x = torch.tensor(x_start, requires_grad=True)
    for n in range(num): 
        y = f(x)
        y.backward()   # 计算梯度
        gx = x.grad.tolist()  # 取出梯度
        newx = x.tolist() - rate*gx # 修正
        x = torch.tensor(newx, requires_grad=True)  #重新定义x, 所以不需要清零操作
        print("X:{x:.2f}, Y:{y:.2f}, gx:{gx:.2f}".format(x=x, y=y,gx=gx))
        if abs(gx)<0.0001:
            break
    return x
        

In [24]:
f = lambda x:x**2

In [25]:
min_gred(2.0, 0.1, 10,f)

X:1.60, Y:4.00, gx:4.00
X:1.28, Y:2.56, gx:3.20
X:1.02, Y:1.64, gx:2.56
X:0.82, Y:1.05, gx:2.05
X:0.66, Y:0.67, gx:1.64
X:0.52, Y:0.43, gx:1.31
X:0.42, Y:0.27, gx:1.05
X:0.34, Y:0.18, gx:0.84
X:0.27, Y:0.11, gx:0.67
X:0.21, Y:0.07, gx:0.54


tensor(0.2147, requires_grad=True)