### 1. 一维数组

In [1]:
import numpy as np

In [2]:
x_list = [1,2,3,4]
type(x_list)

list

In [3]:
x_array = np.array([1,2,3,4])
type(x_array)

numpy.ndarray

In [4]:
x_array.ndim

1

In [5]:
x_array.shape

(4,)

In [6]:
x_array.size

4

In [7]:
x_array.dtype

dtype('int32')

In [8]:
x_sum = 0
for x in x_list:
    x_sum = x_sum+x**2
print(x_sum)

30


In [9]:
sum([x**2 for x in x_list])

30

In [10]:
x_array**2

array([ 1,  4,  9, 16], dtype=int32)

In [11]:
sum(x_array**2)

30

In [12]:
np.ones(4)

array([1., 1., 1., 1.])

In [13]:
np.zeros(4)

array([0., 0., 0., 0.])

In [14]:
np.arange(start=0,stop=1,step=0.2)

array([0. , 0.2, 0.4, 0.6, 0.8])

In [15]:
np.linspace(start=0, stop=1, num=5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### 2.  二维数组

In [16]:
x = np.array([[1,2],[3,4]])
print(x)

[[1 2]
 [3 4]]


In [17]:
x.ndim

2

In [18]:
x.shape

(2, 2)

In [19]:
x.size

4

In [20]:
x = np.zeros([3,3])
print(x)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [21]:
x.shape

(3, 3)

In [22]:
x = np.arange(0,1,0.1)

In [23]:
x.shape

(10,)

In [24]:
x = x.reshape(2,5)

In [25]:
print(x)

[[0.  0.1 0.2 0.3 0.4]
 [0.5 0.6 0.7 0.8 0.9]]


In [26]:
x.shape

(2, 5)

### 3. 数组操作

In [27]:
x = np.arange(0,1,0.1)
print(x)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [28]:
x[0]

0.0

In [29]:
x[-1]

0.9

In [30]:
x[:3]

array([0. , 0.1, 0.2])

In [31]:
x = x.reshape(2,5)
print(x)

[[0.  0.1 0.2 0.3 0.4]
 [0.5 0.6 0.7 0.8 0.9]]


In [32]:
x[0,1]

0.1

In [33]:
x[1,:]

array([0.5, 0.6, 0.7, 0.8, 0.9])

In [34]:
x[:,-1]

array([0.4, 0.9])

In [35]:
x[0,0] = 1

In [36]:
x

array([[1. , 0.1, 0.2, 0.3, 0.4],
       [0.5, 0.6, 0.7, 0.8, 0.9]])

In [37]:
np.append(x,10)

array([ 1. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9, 10. ])

In [38]:
np.insert(x,0,10)

array([10. ,  1. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9])

In [39]:
np.delete(x,-1)

array([1. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8])

In [40]:
y = x>=0.5
print(y)

[[ True False False False False]
 [ True  True  True  True  True]]


In [41]:
x[y]

array([1. , 0.5, 0.6, 0.7, 0.8, 0.9])

In [42]:
x[x>=0.5]

array([1. , 0.5, 0.6, 0.7, 0.8, 0.9])

In [43]:
x[x>=0.5] = 1

In [44]:
x

array([[1. , 0.1, 0.2, 0.3, 0.4],
       [1. , 1. , 1. , 1. , 1. ]])

In [46]:
y = np.arange(10,11,0.1).reshape(2,5)

In [47]:
y

array([[10. , 10.1, 10.2, 10.3, 10.4],
       [10.5, 10.6, 10.7, 10.8, 10.9]])

In [48]:
x = np.concatenate([x,y])

In [51]:
x

array([[ 1. ,  0.1,  0.2,  0.3,  0.4],
       [ 1. ,  1. ,  1. ,  1. ,  1. ],
       [10. , 10.1, 10.2, 10.3, 10.4],
       [10.5, 10.6, 10.7, 10.8, 10.9]])

### 4. 向量化计算

In [52]:
x = np.linspace(0,1,5)
print(x)

[0.   0.25 0.5  0.75 1.  ]


In [53]:
3 * x

array([0.  , 0.75, 1.5 , 2.25, 3.  ])

In [54]:
x/2

array([0.   , 0.125, 0.25 , 0.375, 0.5  ])

In [55]:
x**2 + 2*x - 3

array([-3.    , -2.4375, -1.75  , -0.9375,  0.    ])

In [56]:
np.sin(x)

array([0.        , 0.24740396, 0.47942554, 0.68163876, 0.84147098])

In [57]:
x = np.arange(1,10,dtype=int)
print(x)

[1 2 3 4 5 6 7 8 9]


In [58]:
def odd_even(x):
    if x%2 == 0:
        return "偶数"
    else:
        return "奇数"

In [59]:
odd_even(x)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [60]:
odd_even_v = np.vectorize(odd_even)

In [61]:
print(odd_even_v(x))

['奇数' '偶数' '奇数' '偶数' '奇数' '偶数' '奇数' '偶数' '奇数']


In [62]:
x[x%2==0]

array([2, 4, 6, 8])

In [63]:
x = np.array([[1,0],[1,0]])
print(x)


[[1 0]
 [1 0]]


In [64]:
y = np.array([[0.1,0.2],[0.3,0.4]])
print(y)

[[0.1 0.2]
 [0.3 0.4]]


In [65]:
x.dot(y)

array([[0.1, 0.2],
       [0.1, 0.2]])

### 练习

In [66]:
n = 1000000

In [67]:
from time import time
time_start = time()
sum_list = sum([x for x in range(n) if x%3==0 and x%7==0])
time_end = time()
print("运行时间{x:.4f}秒,和等于{y}".format(x=time_end-time_start,y=sum_list))

运行时间0.1011秒,和等于23809976190


In [68]:
from time import time
time_start = time()
x = np.arange(n,dtype='int64')
sum_array = np.sum(x[(x%3==0)&(x%7==0)])
time_end = time()
print("运行时间{x:.4f}秒,和等于{y}".format(x=time_end-time_start,y=sum_array))

运行时间0.0340秒,和等于23809976190
